### ISSUE TITLE
Add support for page-level metadata

### ISSUE THREAD

**Issue by lcawl** [elastic/docs-builder#95]
Relates to https://github.com/elastic/docs-builder/issues/49 

Our current proposal for representing the version/context of each page in the new information architecture and doc system needs a method for clearly identifying all the contexts that a page is applicable to.

In the current docs system, context needs to be derived from the text itself, the "book" breadcrumbs and version selector. Since books tended to apply to a single product or context, that was usually simpler to infer. For example:

![Image](https://github.com/user-attachments/assets/0a2835c3-ccad-4a1a-ac9f-038d767f63fc)

In the new docs system and information architecture you can't assume pages that are "near" each other are all applicable to the same context, so we should be as clear as possible about the context. For example:

![Image](https://github.com/user-attachments/assets/1c578e1c-66a4-4d69-8f19-41228be0933e)

At this moment, we are proposing that the page-level metadata uses the same deployment type, lifecycle, and version dimensions as described in https://github.com/elastic/docs-builder/issues/94. The assumption being that what is specified at the page-level is applicable to the entire page unless it's overridden by admonitions at the section, page, or line level.

NOTE: We haven't gotten input from the design team yet on the best possible way to make these admonitions informative but not too disruptive. But the vision is informed by the type of "badges" we had in the Serverless docs. 

## Short term

In the short term we would want a consistent way to apply this metadata at a page level and just show them all.
Ideally it would be possible to set this metadata in a configuration file for all the pages in a folder, for example, so that we only needed to set it at a page level if it differed from the default for that content set.

## Long term

In the longer term, we likely need input from design and user feedback on whether it's more useful to only show a subset of contexts (e.g. only show badges that indicate where it *is* supported or vice versa).

In the even longer term, it would be nice to have this metadata affect search and filtering functionality.

**Comment by Mpdreamz** [comment]
Closing this as implemented even though we might go through a few more refinement cycles.
